# Generated by Django 4.1.1 on 2022-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kharif1Paddy2021_one',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gaurdian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('village_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_land', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('previous_crop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_harvest_date', models.DateField(blank=True, null=True)),
                ('area_previous_crop', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('date_chemical_fertilizer', models.DateField(blank=True, null=True)),
                ('qty_urea_46', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('qty_dap_18_46_0', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('qty_fertilizers_12_12_12', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('qty_fertilizer_20_20_0_13', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('amount_manure_mop', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('apply_spraying', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('apply_fertilizing_roots', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('date_cattelmanure_fertilizer', models.DateField(blank=True, null=True)),
                ('cattelmanure_fertilizer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_cattelmanure_fertilizer', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('manure_soil_topping', models.CharField(blank=True, max_length=255, null=True)),
                ('date_apply_ghanamrit', models.DateField(blank=True, null=True)),
                ('qty_greenmanure_ghanamrit', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('crop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('area_farm', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('qty_urea_utilization_46', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('date_urea_use', models.DateField(blank=True, null=True)),
                ('number_2_qty_dap_use_18_46_0', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('number_2_date_dap_18_46_0', models.DateField(blank=True, null=True)),
                ('number_2_qty_use_20_20_0_13', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('number_2_date_access_data_20_20_0_13', models.DateField(blank=True, null=True)),
                ('scr_irrigation', models.CharField(blank=True, max_length=255, null=True)),
                ('method_irrigation', models.CharField(blank=True, max_length=255, null=True)),
                ('natural_remedies', models.CharField(blank=True, max_length=255, null=True)),
                ('date_greenmanure_jeevamrut', models.DateField(blank=True, null=True)),
                ('qty_greenmanure_jeevamrut', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('date_greenmanure_jeevamrut_2', models.DateField(blank=True, null=True)),
                ('qty_greenmanure_jeevamrut_2', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('date_harvest', models.DateField(blank=True, null=True)),
                ('cost_manual_labor_perkatta', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('date_threshing', models.DateField(blank=True, null=True)),
                ('harvest_paddy_yield', models.CharField(blank=True, max_length=255, null=True)),
                ('yield_perkatta', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('total_yield', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('avg_height_plant_before_harvesting', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('height_stalk_lft_after_harvesting_crop', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('date_plowing_back_into_soil', models.DateField(blank=True, null=True)),
                ('date_sowing', models.DateField(blank=True, null=True)),
                ('nursery_sowing_date', models.DateField(blank=True, null=True)),
                ('date_planting_field', models.DateField(blank=True, null=True)),
                ('plowing_the_field', models.DateField(blank=True, null=True)),
                ('depth_of_tillage', models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True)),
                ('irrigation_date_borewell', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
